const SKILL_META={
'责任闭环':['自我管理','自我管理与责任','商业组织 / 公共服务','独立完成职责，并主动检查、收尾和补救。'],
'任务拆解':['元能力','项目管理','AI产品 / 工程系统','把复杂目标拆成5—7个有先后关系的步骤。'],
'深度阅读':['语言表达','阅读与信息提取','科学研究 / 内容传播','提取目标、条件、因果和证据。'],
'反馈与提炼':['元能力','元认知与自主学习','所有专业方向','把一次经历提炼成可重复的方法。'],
'中文书写':['语言表达','书写与写作','内容传播 / 公共表达','在真实成果中做到清楚、准确、有结构。'],
'英文书写':['语言表达','基础英语表达','国际协作 / 技术表达','写清常用标签、单词和简单短句。'],
'打字':['数字表达','数字工具','AI产品 / 内容传播','准确输入、修改、排版并保存版本。'],
'数学预算':['数学数据','数感与资源配置','工程系统 / 商业组织','估算数量、时间、价格和材料约束。'],
'数据分析':['数学数据','记录与解释','科学研究 / 商业分析','持续记录并用数据解释变化。'],
'文件管理':['数字素养','信息与版本管理','AI产品 / 工程系统','建立文件结构、命名、查找和版本规则。'],
'信息可信度':['数字素养','检索与判断','科学研究 / 公共服务','比较来源并说明为什么相信。'],
'计算思维':['数字素养','流程与自动化','AI产品 / 工程系统','把问题转成输入—步骤—条件—输出—测试。'],
'AI协作':['数字素养','人机协作','所有专业方向','先定义目标和标准，再让AI检查和辅助。'],
'用户意识':['社会能力','同理心与服务','产品 / 商业 / 公共服务','让真实使用者测试，并根据反馈修改。'],
'合作分工':['社会能力','合作与责任','组织管理 / 公共服务','明确角色、交接、承诺和冲突处理。'],
'挫折恢复':['自我管理','情绪与恢复','所有专业方向','卡住时说清困难、请求提示并返回任务。'],
'迁移应用':['元能力','举一反三','所有专业方向','把方法用于新场景并说明边界。']};
const PROFESSIONS={
'AI与软件产品':['任务拆解','计算思维','文件管理','AI协作','用户意识','打字'],
'科学与数据':['深度阅读','信息可信度','数据分析','数学预算','反馈与提炼'],
'工程与系统':['任务拆解','数学预算','计算思维','责任闭环','挫折恢复'],
'内容与传播':['深度阅读','中文书写','英文书写','打字','用户意识'],
'商业与组织':['责任闭环','数学预算','合作分工','用户意识','任务拆解'],
'公共服务与领导':['用户意识','合作分工','信息可信度','责任闭环','反馈与提炼']};
const TEMPLATES={
'刘慈欣科幻':{title:'建立家庭刘慈欣科幻档案馆',purpose:'让家人快速找到、理解并推荐家中的科幻书。',steps:['明确家人怎样找书','学习分类、固定位置和标签','设计实体与数字分类规则','整理书架并写清标签','建立数字书目和文件结构','让家人实际查找并收集反馈','修改系统、交付并约定维护'],support:['深度阅读','中文书写','打字','文件管理','用户意识'],maintain:['责任闭环','反馈与提炼'],outputs:['实体分类','数字书目','查找说明','维护规则'],materials:['科幻书','标签纸','电脑'],safety:'控制屏幕时间。'},
'《基督山伯爵》':{title:'破解《基督山伯爵》人物关系',purpose:'把复杂故事讲给家人真正听懂。',steps:['确定听众最需要理解什么','学习人物目标—阻碍—选择—结果五问法','选择关键人物和事件','手绘人物关系和时间线','打字补充人物说明','给真实听众讲解并记录疑问','修改、展示并迁移到语文阅读'],support:['深度阅读','中文书写','打字','用户意识','反馈与提炼'],maintain:['责任闭环'],outputs:['人物图','因果线','讲解','修改记录'],materials:['原书','纸笔','电脑'],safety:'聚焦5—8个关键人物。'},
'Minecraft':{title:'建造极端环境科幻生存基地',purpose:'为一家人在极端环境下设计真正能生活的基地。',steps:['定义环境、居民与生存需求','查资料并列必要系统','手绘平面图与材料预算','拆成多个施工模块','在Minecraft中建造并记录卡点','邀请家人进入基地测试','修改、答辩并进行防守战'],support:['任务拆解','数学预算','计算思维','文件管理','AI协作','用户意识'],maintain:['责任闭环','挫折恢复','中文书写'],outputs:['需求清单','平面图','预算','可用基地','测试记录'],materials:['Minecraft','纸尺','电脑'],safety:'先画图后游戏，不让AI代做全部。'},
'羽毛球':{title:'兄妹羽毛球连续十拍挑战',purpose:'兄妹合作完成十拍，并用数据证明训练有效。',steps:['记录当前基线','学习握拍、击球点和回位','拆分颠球、发球和定点练习','设计一周训练表','记录每天次数和身体状态','分析失败原因并调整','完成挑战、画进步图并教妹妹一招'],support:['数据分析','任务拆解','合作分工','挫折恢复','反馈与提炼'],maintain:['责任闭环'],outputs:['基线','训练表','进步图','挑战结果'],materials:['球拍','羽毛球','计数表'],safety:'胸闷或明显不适立即停止。'},
'家庭做饭':{title:'为家人完成一道拿手菜',purpose:'在预算和时间内完成一道由孩子主导的菜。',steps:['询问家人需求并选择菜品','看菜谱、列清单、估算预算','成人陪同主导采购','练习低风险准备工作','按流程烹饪','家人试吃并反馈','清理归位、总结并修改菜谱'],support:['数学预算','责任闭环','用户意识','任务拆解','合作分工'],maintain:['中文书写','反馈与提炼'],outputs:['清单','预算','流程卡','成品菜','清理记录'],materials:['菜谱','食材','厨房工具'],safety:'刀具、热油和明火由成人近距离控制。'},
'故事会':{title:'制作自己的《少年故事会》',purpose:'把真实生活小事写成家人愿意读完的故事。',steps:['寻找有变化的生活小事','读短故事并分析冲突和结尾','口述故事并列三段提纲','手写关键段落','打字完成并修改','让家人阅读并反馈','修改、配图并发布'],support:['深度阅读','中文书写','打字','用户意识','反馈与提炼'],maintain:['责任闭环','挫折恢复'],outputs:['提纲','手写样本','电子故事','读者反馈'],materials:['故事会','纸笔','电脑'],safety:'保留孩子自己的语气。'},
'地理探索':{title:'设计一次家庭低成本探索路线',purpose:'设计一条真正可走、预算合理的路线。',steps:['确定对象、时间和限制','查地图与地点信息','比较路线、交通和预算','制作行程与物品清单','实地执行并记录','家人评价哪里不方便','修改为可复用攻略'],support:['信息可信度','数学预算','任务拆解','用户意识','数据分析'],maintain:['责任闭环','中文书写'],outputs:['路线图','预算表','清单','实地记录'],materials:['地图','手机','纸笔'],safety:'路线和交通由成人最终确认。'},
'塞尔达探索':{title:'制作《王国之泪》探索者攻略',purpose:'把游戏经验整理成家人能使用的攻略。',steps:['确定攻略对象和主题','记录真实探索问题','学习地图、图标和步骤表达','制作第一版路线图','实际按攻略验证','让别人试用并反馈','修改并迁移到现实路线规划'],support:['任务拆解','用户意识','中文书写','文件管理','反馈与提炼'],maintain:['责任闭环','迁移应用'],outputs:['问题清单','路线图','图标说明','实测攻略'],materials:['游戏','纸笔','截图'],safety:'先确定成果后游戏。'}};
const SHELLS=Object.keys(TEMPLATES),SKILLS=Object.keys(SKILL_META),KEY='growthOS';
let memory=null,persistent=true,chosenShell='刘慈欣科幻',chosenSkills=['责任闭环','任务拆解'];
const el=id=>document.getElementById(id),uniq=a=>[...new Set(a.filter(Boolean))],id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function sget(){try{return localStorage.getItem(KEY)}catch(e){persistent=false;return memory}}
function sset(v){memory=v;try{localStorage.setItem(KEY,v);persistent=true}catch(e){persistent=false}}
function fresh(){return{version:2,child:{name:'孩子A',age:'9岁 · 即将四年级',interests:['刘慈欣科幻','故事','地理','漫画经济学','Minecraft','羽毛球'],focus:[{name:'责任闭环',desc:'从提醒走向主动补救'},{name:'反馈与提炼',desc:'把阅读转化为总结和迁移'},{name:'中文书写',desc:'进入真实输出场景'}],resources:['《基督山伯爵》','刘慈欣科幻与漫画版《三体》','地理与漫画经济学','Minecraft教育版','电脑','羽毛球器材']},skills:Object.fromEntries(SKILLS.map(k=>[k,{level:['深度阅读','打字'].includes(k)?2:1,evidence:[]}])) ,task:null,reviews:[]}}
function load(){let x=null;try{x=JSON.parse(sget()||'null')}catch(e){};const f=fresh();if(!x)return f;if(x.child)f.child={...f.child,...x.child};if(x.skills)for(const k of SKILLS)if(x.skills[k])f.skills[k]={level:Number(x.skills[k].level||0),evidence:x.skills[k].evidence||[]};if(x.skillLevels)for(const[k,v]of Object.entries(x.skillLevels))if(f.skills[k])f.skills[k].level=v;f.reviews=x.reviews||[];f.task=x.task&&x.task.coreSkills?x.task:null;return f}
let state=load();
function focusSkills(){const t=state.child.focus.map(x=>x.name+x.desc).join('');return uniq([t.includes('责任')?'责任闭环':'',t.includes('总结')||t.includes('提炼')?'反馈与提炼':'',t.includes('书写')?'中文书写':'',t.includes('整理')?'文件管理':'',t.includes('迁移')?'迁移应用':''])}
function buildTask(shell,core,user,problem,time){const t=TEMPLATES[shell],c=uniq(core).slice(0,3),sup=uniq([...t.support,...focusSkills()]).filter(x=>!c.includes(x)).slice(0,6),maint=uniq(t.maintain).filter(x=>!c.includes(x)&&!sup.includes(x)),ph=['明确真实目的','学习必要方法','设计方案','完成第一部分','完成第二部分','真实用户测试','交付与迁移'],stand=['能说清给谁用、解决什么、怎样算成功。','能复述方法并完成一个小样例。','形成别人看得懂的清单、草图或流程。','出现可见的第一版成果并记录问题。','核心成果基本完成并说明仍缺什么。','真实使用者实际试用并留下反馈。','根据反馈修改、收尾、归档并说明迁移。'];return{id:id(),title:t.title,purpose:`${t.purpose} 真实使用者：${user}。家庭情境：${problem}`,shell,coreSkills:c,supportSkills:sup,maintenanceSkills:maint,outputs:t.outputs,safety:t.safety,steps:t.steps.map((x,i)=>({title:x,phase:ph[i],child:x,parent:i===0?'只问清目的，不急着教工具。':i===1?'只示范一个最小样例。':'只在真实卡点给一个提示。',elder:i===5?'作为真实使用者说事实反馈。':'提醒一次、守安全、不代做。',duration:Math.max(15,Math.round(Number(time)*(i===3||i===4?1:.65))),evidence:i===5?'真实用户反馈':i===6?'最终成果＋方法卡':'阶段照片/文件/数据',standard:stand[i],skills:uniq([c[i%c.length],sup[i%sup.length]]),done:false,note:''}))}}
if(!state.task)state.task=buildTask('刘慈欣科幻',['责任闭环','任务拆解'],'妹妹和爷爷奶奶','家里的科幻书需要更好整理。',35);
function save(){sset(JSON.stringify(state))}
function metric(n,l,c){return`<div class="metric"><label><b>${n}</b><span>${l}/5</span></label><div class="progress"><div class="bar" style="width:${l*20}%;background:${c}"></div></div></div>`}
function matrix(t){const g=(n,a,c)=>`<div class="matrix-group ${c}"><div class="matrix-title">${n}</div><div class="matrix-tags">${a.map(x=>`<span class="pill ${c==='support'?'green':c==='maintain'?'orange':''}">${x}</span>`).join('')}</div></div>`;return`<div class="matrix">${g('核心训练',t.coreSkills,'core')}${g('重要支撑',t.supportSkills,'support')}${g('基础维护',t.maintenanceSkills,'maintain')}</div>`}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));el(p).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const title={home:['成长OS','让每个真实任务都长出能力'],profile:['孩子画像','画像真正参与任务编译'],skills:['技能树','从基础能力追溯到未来能力'],generator:['项目编译器','兴趣外壳 × 能力缺口 × 家庭资源'],workflow:['完整工作流','孩子、家长、老人各自知道怎么做'],review:['证据与迁移','反馈成为升级依据']}[p];el('pageTitle').textContent=title[0];el('pageSub').textContent=title[1];({home:renderHome,profile:renderProfile,skills:renderSkills,generator:renderGenerator,workflow:renderWorkflow,review:renderReview}[p])();scrollTo(0,0)}
function renderHome(){const t=state.task,d=t.steps.filter(x=>x.done).length,n=t.steps.length,next=t.steps.find(x=>!x.done)||t.steps.at(-1);el('childBadge').textContent=`哥哥 · ${state.child.age.split(' · ')[0]}`;el('currentTaskTitle').textContent=t.title;el('taskProgressText').textContent=`已推进 ${d} / ${n} 步`;el('taskProgressBar').style.width=`${d/n*100}%`;el('todayStep').textContent=next.child;el('todayStandard').textContent=`完成标准：${next.standard}`;el('homeMatrix').innerHTML=matrix(t);el('homeSkills').innerHTML=state.child.focus.slice(0,3).map((x,i)=>metric(x.name,state.skills[x.name]?.level||0,['var(--green)','var(--purple)','var(--blue)'][i])).join('')}
function renderProfile(){el('profileName').textContent=state.child.name;el('profileAge').textContent=state.child.age;el('profileInterests').innerHTML=state.child.interests.map(x=>`<span class="pill">${x}</span>`).join('');el('profileFocus').innerHTML=state.child.focus.map(x=>`<div class="card evidence"><b>${x.name}</b><div class="small">${x.desc}</div></div>`).join('');el('profileResources').innerHTML=state.child.resources.map(x=>'• '+x).join('<br>')}
function profLevel(a){return Math.round(a.reduce((s,k)=>s+(state.skills[k]?.level||0),0)/a.length)}
function canUpgrade(k){const n=state.skills[k],strong=n.evidence.filter(e=>e.strong);return n.level===0?n.evidence.length>0:n.level===1?strong.length>=1:n.level===2?strong.length>=3:new Set(strong.map(e=>e.shell)).size>=2}
function renderSkills(){const colors=['var(--primary)','var(--blue)','var(--orange)','var(--purple)','var(--green)','var(--red)'];el('professionSkills').innerHTML=Object.entries(PROFESSIONS).map(([k,v],i)=>metric(k,profLevel(v),colors[i])).join('');el('skillList').innerHTML=SKILLS.map(k=>{const m=SKILL_META[k],n=state.skills[k],ok=canUpgrade(k);return`<div class="skill-card"><div class="skill-head"><div><div class="skill-name">${k}</div><div class="skill-path">${m[0]} → ${m[1]} → ${m[2]}</div></div><span class="level-badge">${n.level}/5</span></div><div class="small">下一等级证据：${m[3]}</div><div class="skill-evidence"><span class="${ok?'eligible':'not-eligible'}">${ok?'已满足升级建议':`已有 ${n.evidence.length} 条证据`}</span>${ok?`<button class="btn small-btn green" onclick="confirmUpgrade('${k}')">家长确认升级</button>`:''}</div></div>`}).join('')}
function confirmUpgrade(k){if(!canUpgrade(k))return;state.skills[k].level=Math.min(5,state.skills[k].level+1);save();renderSkills();renderHome()}
function renderGenerator(){el('profileSignal').innerHTML=`<b>系统正在读取画像</b><div class="small">兴趣：${state.child.interests.join('、')}<br>重点：${state.child.focus.map(x=>x.name).join('、')}<br>资源：${state.child.resources.slice(0,4).join('、')}……</div>`;el('shellTags').innerHTML=SHELLS.map(x=>`<button class="tag ${x===chosenShell?'selected':''}" onclick="selectShell('${x.replaceAll("'","\\'")}')">${x}</button>`).join('');el('skillTags').innerHTML=SKILLS.map(x=>`<button class="tag skill ${chosenSkills.includes(x)?'selected':''}" onclick="toggleSkill('${x}')">${x}</button>`).join('')}
function selectShell(x){chosenShell=x;renderGenerator()}function toggleSkill(x){chosenSkills=chosenSkills.includes(x)?chosenSkills.filter(k=>k!==x):(chosenSkills.length<3?[...chosenSkills,x]:chosenSkills);renderGenerator()}
function generateTask(){const t=buildTask(chosenShell,chosenSkills,el('realUser').value.trim()||'家人',el('realProblem').value.trim()||'解决一个真实问题',el('availableTime').value);el('generatedTask').innerHTML=`<div class="card"><span class="pill green">编译完成</span><h2>${t.title}</h2><p class="small">${t.purpose}</p>${matrix(t)}<p class="small"><b>交付：</b>${t.outputs.join('、')}<br><b>安全：</b>${t.safety}</p><button id="useTaskBtn" class="btn full">使用这个任务</button></div>`;el('useTaskBtn').onclick=()=>{state.task=t;save();go('workflow')}}
function renderWorkflow(){const t=state.task;el('wfTitle').textContent=t.title;el('wfPurpose').textContent=t.purpose;el('wfMatrix').innerHTML=matrix(t);el('steps').innerHTML=t.steps.map((s,i)=>`<div class="task-step ${s.done?'done':''}"><div class="step-dot">${s.done?'✓':i+1}</div><div class="step-body"><span class="pill gray">${s.phase}</span><h3>${s.title}</h3><p><b>本步目的：</b>${s.standard}</p><div class="step-meta"><div class="meta-box"><b>预计时间</b><br>${s.duration}分钟</div><div class="meta-box"><b>留下证据</b><br>${s.evidence}</div></div><div class="detail-block"><p><b>孩子：</b>${s.child}</p><p><b>家长：</b>${s.parent}</p><p><b>老人：</b>${s.elder}</p><p><b>本步能力：</b>${s.skills.join('、')}</p></div><textarea class="step-note" placeholder="记录卡点或证据" onchange="setStepNote(${i},this.value)">${s.note}</textarea><label class="checkline"><input type="checkbox" ${s.done?'checked':''} onchange="toggleStep(${i},this.checked)"> 已完成、检查并收尾</label></div></div>`).join('')}
function setStepNote(i,v){state.task.steps[i].note=v;save()}function toggleStep(i,v){state.task.steps[i].done=v;save();renderWorkflow();renderHome()}function saveWorkflow(){save();alert('进度已保存。')}
function renderReview(){const d=state.task.steps.filter(x=>x.done).length,n=state.task.steps.length;el('reviewGate').innerHTML=`当前任务完成 <b>${d}/${n}</b> 步。只有全部完成、真实测试、修改且主要独立完成，才算强证据。`;renderReviews();el('reviewResult').innerHTML=''}
function saveReview(){const r={id:id(),date:new Date().toISOString(),task:state.task.title,shell:state.task.shell,evidenceType:el('evidenceType').value,independence:Number(el('independence').value),userTest:el('userTest').checked,revised:el('revised').checked,taught:el('taught').checked,feedback:el('fb').value.trim(),summary:el('sum').value.trim(),abstract:el('abs').value.trim(),apply:el('apply').value.trim(),transfer:el('transfer').value.trim()};r.score=[state.task.steps.every(x=>x.done)?2:0,r.evidenceType?1:0,r.independence>=2?1:0,r.userTest?1:0,r.revised?1:0,r.feedback.length>=8?1:0,r.summary.length>=8?1:0,r.abstract.length>=6?1:0,r.apply.length>=6?1:0,r.transfer.length>=8?1:0,r.taught?1:0].reduce((a,b)=>a+b,0);r.strong=state.task.steps.every(x=>x.done)&&r.independence>=2&&r.userTest&&r.revised&&r.score>=9;state.reviews.unshift(r);[...state.task.coreSkills,...state.task.supportSkills].forEach(k=>state.skills[k]?.evidence.push({date:r.date.slice(0,10),shell:r.shell,strong:r.strong,transfer:r.transfer}));save();renderReviews();el('reviewResult').innerHTML=`<div class="card"><div class="row between"><div><b>本次证据质量</b><div class="small">${r.strong?'强证据，可用于升级判断':'普通证据，暂不支持升级'}</div></div><div class="review-score">${r.score}/12</div></div></div>`;alert('已保存证据，技能不会自动升级。')}
function renderReviews(){el('reviewHistory').innerHTML=state.reviews.length?'<div class="section-title">历史证据</div>'+state.reviews.map(r=>`<div class="card"><div class="row between"><span class="pill purple">${new Date(r.date).toLocaleDateString()}</span><span class="pill ${r.strong?'green':'gray'}">${r.strong?'强证据':'普通证据'} ${r.score}/12</span></div><h3>${r.task}</h3><div class="small"><b>反馈：</b>${r.feedback||'未填写'}<br><b>提炼：</b>${r.abstract||'未填写'}<br><b>迁移：</b>${r.transfer||'未填写'}</div></div>`).join(''):'<div class="empty">还没有证据记录。</div>'}
function openGuide(){const s=state.task.steps.find(x=>!x.done)||state.task.steps.at(-1);el('sheet').innerHTML=`<div class="row between"><h2>今晚10分钟教学脚本</h2><button class="btn ghost" onclick="closeModal()">关闭</button></div><hr><p><b>当前步骤：${s.title}</b></p><p class="small">${s.standard}</p><p><b>1. 复述目的</b></p><p class="small">给谁用？做完看到什么？</p><p><b>2. 最小示范</b></p><p class="small">${s.parent}</p><p><b>3. 孩子接手</b></p><p class="small">只问：下一步准备做什么？</p><p><b>4. 留下证据</b></p><p class="small">${s.evidence}</p>`;el('modal').classList.add('open')}
function editProfile(){el('sheet').innerHTML=`<div class="row between"><h2>编辑孩子画像</h2><button class="btn ghost" onclick="closeModal()">关闭</button></div><div class="field"><label>姓名</label><input id="edName" value="${state.child.name}"></div><div class="field"><label>年龄阶段</label><input id="edAge" value="${state.child.age}"></div><div class="field"><label>兴趣（逗号分隔）</label><textarea id="edInterests">${state.child.interests.join('，')}</textarea></div><div class="field"><label>成长重点：每行“能力|描述”</label><textarea id="edFocus">${state.child.focus.map(x=>`${x.name}|${x.desc}`).join('\n')}</textarea></div><div class="field"><label>家庭资源（每行一项）</label><textarea id="edResources">${state.child.resources.join('\n')}</textarea></div><button class="btn full" onclick="saveProfile()">保存并用于任务编译</button><hr><div class="grid2"><button class="btn secondary" onclick="exportData()">导出数据</button><button class="btn ghost" onclick="importData()">导入数据</button></div>`;el('modal').classList.add('open')}
function saveProfile(){state.child.name=el('edName').value.trim()||'孩子A';state.child.age=el('edAge').value.trim();state.child.interests=el('edInterests').value.split(/[，,]/).map(x=>x.trim()).filter(Boolean);state.child.focus=el('edFocus').value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const[n,...d]=x.split('|');return{name:n.trim(),desc:d.join('|').trim()||'继续观察'}});state.child.resources=el('edResources').value.split('\n').map(x=>x.trim()).filter(Boolean);save();renderProfile();closeModal()}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='成长OS数据.json';a.click()}function importData(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const r=new FileReader();r.onload=()=>{try{sset(JSON.stringify(JSON.parse(r.result)));location.reload()}catch(e){alert('文件格式不正确')}};r.readAsText(i.files[0])};i.click()}function closeModal(){el('modal').classList.remove('open')}
window.addEventListener('DOMContentLoaded',()=>{el('editProfileBtn')?.addEventListener('click',editProfile);renderHome();renderProfile();renderSkills();renderGenerator();renderWorkflow();renderReview()});
